name: calendar
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  build_runner: ^2.4.6
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0
  mobx_codegen: ^2.3.0
  shared_preferences: ^2.2.2
  easy_localization: ^3.0.3
  get_it: ^7.6.4
  json_annotation: ^4.8.1
  injectable: ^2.3.2
  devicelocale: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/translations/

 